mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coffee_menu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto=update:
